
CREATE TABLE `users` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `FNAME` varchar(255) NOT NULL,
 `LNAME` varchar(255) NOT NULL,
 `EMAIL_ID` varchar(255) NOT NULL,
 `PASSWORD` varchar(255) NOT NULL,
 `IS_DELETED` int(11) NOT NULL DEFAULT 0,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

CREATE TABLE `school_details` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `USER_ID` int(11) NOT NULL,
 `SCHOOL_NAME` varchar(255) NOT NULL,
 `LOCATION` varchar(255) NOT NULL,
 `IS_DELETED` int(11) NOT NULL DEFAULT 0,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;


